### ISSUE TITLE
Add True Color Imagery to background settings in iD editor

### ISSUE THREAD

**Issue by WillieShubert** [crowdcover/logging-roads#1]
It would be great to have the option to view true color satellite images as one of the options in the map data menu. It would be a helpful reference to make sure that edits are not truly off base.

**Comment by jameslaneconkling** [comment]
Great idea.  We're working on getting SPOT imagery licensing, but even if
we fail to get that licensed, we could add a Bing or MapBox imagery layer.

Post if you have any other open imagery tms sources you think would be
helpful.

**Comment by jameslaneconkling** [comment]
Added MapBox satellite imagery as default.  Closing for now.

(feel free to re-open if you have more suggestions)
