### ISSUE TITLE
Project Contact Email?

### ISSUE THREAD

**Issue by jameslaneconkling** [crowdcover/logging-roads#14]
right now, the **contact us** button links to my email address.

Should we set up an info@loggingroads.org email address?

**Comment by jameslaneconkling** [comment]
@thomas-maschler , thoughts?

**Comment by kriscarle** [comment]
Going through old tickets... It sounds like we just want to have a something like info@loggingroads.org forward to certain real emails? Here is a way to do that http://www.binarytides.com/postfix-mail-forwarding-debian/ We would run that on the loggingroads.org server and it would forward the emails wherever we want.
