### ISSUE TITLE
Partners text

### ISSUE THREAD

**Issue by BKessle** [crowdcover/logging-roads#29]
The "PARTNERS" text color at the bottom of the homepage is very hard to make out against the background.

**Comment by kriscarle** [comment]
I agree we need to increase the contrast in the partners section, possibly by wrapping that section in a lighter color box. @jameslaneconkling any ideas?

![image](https://cloud.githubusercontent.com/assets/2431570/9209313/c9f3cfa8-4043-11e5-892f-223bf2978d14.png)

**Comment by kriscarle** [comment]
Here is my attempt to update this
![image](https://cloud.githubusercontent.com/assets/2431570/10080629/a92981f8-62be-11e5-9d9c-58182175688e.png)
