### ISSUE TITLE
Add tutorial video

### ISSUE THREAD

**Issue by thomas-maschler** [crowdcover/logging-roads#42]
Tutorial video is stored here.
https://wri-forest-atlas.s3.amazonaws.com/Team/Projects/OSM/Documentation/LRI%20Tutorial%20.mp4

We might need to compress it a bit more.
There are some details we should add as overlays
- type logging roads in the search bar to get the right tags right away
- don't use WRI as source but Landsat

**Comment by jameslaneconkling** [comment]
@thomas-maschler this looks great, thanks.

As an FYI, I'm going back to school for the summer, and so probably won't be able to do any active development/maintenance until I'm done in October.  I know Leo is putting together some sort of RFP for the project 2.0; assuming I'll rejoin the project in the fall in either an official or unofficial capacity (depending on where I am).

**Comment by jameslaneconkling** [comment]
@thomas-maschler sorry for the delay on this.

Have been doing some updates on the site today.  Hopefully will have it all deployed tomorrow/early next week.

**Comment by thomas-maschler** [comment]
Thanks James.
Also good luck for your school. Hope to have you back in the winter!

**Comment by jameslaneconkling** [comment]
Just deployed (at long last).  Ended up uploading the video to youtube, so we could keep it out of the git repo.

**Comment by thomas-maschler** [comment]
Thanks James,

This looks great.
Can you share the video with me?
I’d like to add some YouTube annotations to it.

Thanks,

Thomas

**Comment by jameslaneconkling** [comment]
The video's posted [here](https://www.youtube.com/watch?v=pGsTtQgV57U).  Do
I need to grant you any special permissions w/i youtube to allow you to
annotate it?

**Comment by thomas-maschler** [comment]
Yes, I will need some kind of write permission to add annotations

**Comment by jameslaneconkling** [comment]
What's your gmail/google+ account name?

**Comment by jameslaneconkling** [comment]
actually, just realized this won't work: it's not possible to add
contributors to personal youtube accounts, and I can't transfer the video
from my account to an organization account.  See:
https://support.google.com/youtube/answer/2404846?hl=en

But, if you upload the video to youtube (either your own account or an
organization account you create for the project), you'll be able to edit.
I can then update the link.

**Comment by thomas-maschler** [comment]
Ok. Thanks for letting me know.

Sent from OWA on Android
