### ISSUE TITLE
Clarify license of generated data

### ISSUE THREAD

**Issue by almccon** [crowdcover/logging-roads#43]
I see on the home page of loggingroads.org it says that the data will be released in the "public domain". But as far as I can tell, the data is only going into OpenStreetMap, which uses the Creative Commons-like Open Database License. In a technical legal sense, the ODbL is _not_ Public Domain. 

Are there plans to collect the logging roads data in a separate public domain database _before_ loading it into OSM? If not, then the main page should be changed to be similar to the [about](loggingroads.org/about) page and a phrase something like "Creative Commons" and not "Public Domain".

**Comment by jameslaneconkling** [comment]
@almccon thanks for pointing this out--should have caught it myself.

I updated to 'Creative Commons': 18b95d36c5d26d0e29a7b8d7350bef04828475c9.

Will deploy the changes soon.

Thanks for posting.

**Comment by jameslaneconkling** [comment]
Just deployed.  Thanks again.
