### ISSUE TITLE
Enable UI translation in iD editor

### ISSUE THREAD

**Issue by thomas-maschler** [crowdcover/logging-roads#50]
iD editor has a translated interface. It normally fetches the user settings from OSM and uses user's preferred language. This doesn't work for our iD instance. Everything stays in English

**Comment by kriscarle** [comment]
When iD is running on its own (not inside OSM's homepage) it uses the computer language settings not the OSM profile settings. I was able to get the logging roads iD to change languages by changing the primary language of my computer to French, restarting Chrome, then going to Settings -> Advanced Settings -> Languages and dragging French to the top of the list. (other browsers have similar settings).

![image](https://cloud.githubusercontent.com/assets/2431570/10589945/33a8914a-767c-11e5-9cb9-535227dcf6cf.png)

**Comment by kriscarle** [comment]
For iD to use the preferred order of languages from the browser, instead of the primary computer language, it would need to be updated to use navigator.languages instead of navigator.language, see https://alicoding.com/detect-browser-language-preference-in-firefox-and-chrome-using-javascript/

**Comment by kriscarle** [comment]
Fixed in https://github.com/loggingroads/iD/commit/33fffec505c8c34552934ba1dba5c8fccb4a7e3e
